### ISSUE TITLE
Server Connection Crash: Trying to pull content from your gitlab instance?

### ISSUE THREAD

**Issue by cwingrav** [Bixilon/Minosoft#22]
Trying it out. I built it locally on master, started a server locally (1.20.2), and in your client I added a server. It sees the local server just fine. When I connect to a server, I get this error below. I can connect to the locally running server just fine in the official Minecraft Vanilla 1.20.2 client.

Is it trying to reach out to your local server? Is there a was to modify the config to go to gitlab.com or maybe my local machine?

Thanks in advance. I'd love to see a faster client!

```
java.io.IOException: Server returned HTTP response code: 502 for URL: https://gitlab.bixilon.de/bixilon/pixlyzer-data/-/raw/master/hash/e9/e974834ee9d0ae154070533be75225add765241b.mbf?inline=false
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1585)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1162)
	at de.bixilon.minosoft.data.registries.registries.PixLyzerUtil.verify(PixLyzerUtil.kt:43)
	at de.bixilon.minosoft.data.registries.registries.PixLyzerUtil.loadPixlyzerData(PixLyzerUtil.kt:55)
	at de.bixilon.minosoft.data.registries.registries.PixLyzerUtil.loadRegistry(PixLyzerUtil.kt:60)
	at de.bixilon.minosoft.data.registries.registries.RegistriesLoader.load(RegistriesLoader.kt:25)
	at de.bixilon.minosoft.protocol.versions.Version.load(Version.kt:46)
	at de.bixilon.minosoft.protocol.network.connection.play.PlayConnection$connect$2.invoke(PlayConnection.kt:193)
	at de.bixilon.minosoft.protocol.network.connection.play.PlayConnection$connect$2.invoke(PlayConnection.kt:191)
	at de.bixilon.kutil.concurrent.worker.task.TaskWorker.work$lambda$3(TaskWorker.kt:108)
	at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.run(ThreadPoolExecutor.kt:25)
	at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.execute(ThreadPoolExecutor.kt:44)
	at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.loop(ThreadPoolThread.kt:49)
	at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.run(ThreadPoolThread.kt:31)
```

**Comment by BitesizedLion** [comment]
As far as I understand it, you'd need to edit https://github.com/Bixilon/Minosoft/blob/master/src/main/java/de/bixilon/minosoft/config/profile/profiles/resources/source/SourceC.kt and build it yourself.

**Comment by Bixilon** [comment]
You can change the download url (`pixlyzer`) in the config (`~/.config/minosoft/minosoft/resources/Default.json`) to `https://github.com/Bixilon/pixlyzer-data/raw/master/hash/${hashPrefix}/${fullHash}.mbf` for the moment.

My gitlab instance totally exploded this night, insane. Gitlab is poorly optimized. Should by up by now.

I think I need to add 2 download links in the config and use failover.

**Comment by Bixilon** [comment]
Thanks for reporting this, not sure how to make my gitlab more performant without throwing a lot of money into it, but that should do the trick.

gitlab.bixilon.de/bixilon/minosoft will still redirect to github.com,  I am monitoring the situation and I will restore it.

**Comment by cwingrav** [comment]
Ah, your personal gitlab was crashed due to the Hacker News post probably.

To fix this, I replaced the server in ./src/main/java/de/bixilon/minosoft/config/profile/profiles/resources/source/SourceC.kt with "https://github.com".

I love that load time. When modding, i'd love faster ways to restart minecraft. I'll keep watching your project. Keep at it!

**Comment by Bixilon** [comment]
Yes, that file is the kotlin representation of the configuration file.

Its pretty fast, but it can still be optimized. I took a look at the timeline graph. But not in next time, fast enough for now.
