### ISSUE TITLE
Versions file not found!

### ISSUE THREAD

**Issue by QaisMalkawi** [Bixilon/Minosoft#26]
Hello, I appreciate the work you did,
Iam facing this issue here while running the build:
```
[2023-12-17 00:29:27.913] [main] [OTHER] [INFO] Starting minosoft...
[2023-12-17 00:29:28.581] [Worker#10] [OTHER] [FATAL] Can not load version.json! Did you compile with gradle?
[2023-12-17 00:29:28.583] [Worker#10] [OTHER] [INFO] This is minosoft version unknown!
```

I searched the file and found two instances:
\..\minosoft\src\main\resources\assets\minosoft\mapping\versions.json
\..\minosoft\build\resources\main\assets\minosoft\mapping\versions.json

**Comment by QaisMalkawi** [comment]
Full Log:
```
> Task :run
[2023-12-17 00:29:27.913] [main] [OTHER] [INFO] Starting minosoft...
[2023-12-17 00:29:28.581] [Worker#10] [OTHER] [FATAL] Can not load version.json! Did you compile with gradle?
[2023-12-17 00:29:28.583] [Worker#10] [OTHER] [INFO] This is minosoft version unknown!
[2023-12-17 00:29:28.625] [Worker#2] [OTHER] [WARN] java.io.FileNotFoundException: Can not find asset minosoft:mapping/versions.json
[2023-12-17 00:29:28.626] [Worker#2] [OTHER] [WARN]      at de.bixilon.minosoft.assets.directory.DirectoryAssetsManager.get(DirectoryAssetsManager.kt:82)
[2023-12-17 00:29:28.626] [Worker#2] [OTHER] [WARN]      at de.bixilon.minosoft.protocol.versions.VersionLoader.load(VersionLoader.kt:89)
[2023-12-17 00:29:28.627] [Worker#2] [OTHER] [WARN]      at de.bixilon.minosoft.main.MinosoftBoot$register$1.invoke(MinosoftBoot.kt:39)
[2023-12-17 00:29:28.628] [Worker#2] [OTHER] [WARN]      at de.bixilon.minosoft.main.MinosoftBoot$register$1.invoke(MinosoftBoot.kt:39)
[2023-12-17 00:29:28.628] [Worker#2] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.worker.task.TaskWorker.work$lambda$3(TaskWorker.kt:113)
[2023-12-17 00:29:28.628] [Worker#2] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.run(ThreadPoolExecutor.kt:25)
[2023-12-17 00:29:28.628] [Worker#2] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.execute(ThreadPoolExecutor.kt:44)
[2023-12-17 00:29:28.628] [Worker#2] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.loop(ThreadPoolThread.kt:49)
[2023-12-17 00:29:28.628] [Worker#2] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.run(ThreadPoolThread.kt:31)
[2023-12-17 00:29:28.630] [Worker#8] [OTHER] [WARN] java.io.FileNotFoundException: Can not find asset mojang:yggdrasil/pubkey.der
[2023-12-17 00:29:28.631] [Worker#8] [OTHER] [WARN]      at de.bixilon.minosoft.assets.directory.DirectoryAssetsManager.get(DirectoryAssetsManager.kt:82)
[2023-12-17 00:29:28.631] [Worker#8] [OTHER] [WARN]      at de.bixilon.minosoft.util.yggdrasil.YggdrasilUtil.load(YggdrasilUtil.kt:39)
[2023-12-17 00:29:28.631] [Worker#8] [OTHER] [WARN]      at de.bixilon.minosoft.main.MinosoftBoot$register$6.invoke(MinosoftBoot.kt:48)
[2023-12-17 00:29:28.631] [Worker#8] [OTHER] [WARN]      at de.bixilon.minosoft.main.MinosoftBoot$register$6.invoke(MinosoftBoot.kt:48)
[2023-12-17 00:29:28.632] [Worker#8] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.worker.task.TaskWorker.work$lambda$3(TaskWorker.kt:113)
[2023-12-17 00:29:28.632] [Worker#8] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.run(ThreadPoolExecutor.kt:25)
[2023-12-17 00:29:28.632] [Worker#8] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.execute(ThreadPoolExecutor.kt:44)
[2023-12-17 00:29:28.632] [Worker#8] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.loop(ThreadPoolThread.kt:49)
[2023-12-17 00:29:28.632] [Worker#8] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.run(ThreadPoolThread.kt:31)
[2023-12-17 00:29:28.645] [Worker#3] [OTHER] [WARN] java.io.FileNotFoundException: Can not find asset minosoft:fixer/block_entity.json
[2023-12-17 00:29:28.645] [Worker#3] [OTHER] [WARN]      at de.bixilon.minosoft.assets.directory.DirectoryAssetsManager.get(DirectoryAssetsManager.kt:82)
[2023-12-17 00:29:28.645] [Worker#3] [OTHER] [WARN]      at de.bixilon.minosoft.datafixer.rls.ResourceLocationFixer.load(ResourceLocationFixer.kt:28)
[2023-12-17 00:29:28.645] [Worker#3] [OTHER] [WARN]      at de.bixilon.minosoft.datafixer.DataFixer.load(DataFixer.kt:33)
[2023-12-17 00:29:28.645] [Worker#3] [OTHER] [WARN]      at de.bixilon.minosoft.main.MinosoftBoot$register$9.invoke(MinosoftBoot.kt:52)
[2023-12-17 00:29:28.645] [Worker#3] [OTHER] [WARN]      at de.bixilon.minosoft.main.MinosoftBoot$register$9.invoke(MinosoftBoot.kt:52)
[2023-12-17 00:29:28.647] [Worker#3] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.worker.task.TaskWorker.work$lambda$3(TaskWorker.kt:113)
[2023-12-17 00:29:28.647] [Worker#3] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.run(ThreadPoolExecutor.kt:25)
[2023-12-17 00:29:28.647] [Worker#3] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.execute(ThreadPoolExecutor.kt:44)
[2023-12-17 00:29:28.647] [Worker#3] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.loop(ThreadPoolThread.kt:49)
[2023-12-17 00:29:28.647] [Worker#3] [OTHER] [WARN]      at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.run(ThreadPoolThread.kt:31)
[2023-12-17 00:29:28.958] [CLI] [OTHER] [WARN] Dec 17, 2023 12:29:28 AM org.jline.utils.Log logr
[2023-12-17 00:29:28.958] [CLI] [OTHER] [WARN] WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
[2023-12-17 00:29:28.958] [CLI] [OTHER] [WARN]
[2023-12-17 00:29:29.535] [JavaFX Application Thread] [OTHER] [WARN] Exception in Application start method
[2023-12-17 00:29:29.545] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL] java.lang.RuntimeException: Exception in Application start method
[2023-12-17 00:29:29.545] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
[2023-12-17 00:29:29.545] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at java.base/java.lang.Thread.run(Thread.java:842)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL] Caused by: java.io.FileNotFoundException: Can not find asset minosoft:textures/icons/window_icon.png
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at de.bixilon.minosoft.assets.directory.DirectoryAssetsManager.get(DirectoryAssetsManager.kt:82)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at de.bixilon.minosoft.gui.eros.util.JavaFXInitializer.start(JavaFXInitializer.kt:42)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
[2023-12-17 00:29:29.547] [JavaFX Toolkit Initializing Thread] [OTHER] [FATAL]       ... 1 more
<===========--> 85% EXECUTING [14m 9s]
```

**Comment by Bixilon** [comment]
> [2023-12-17 00:29:28.581] [Worker#10] [OTHER] [FATAL] Can not load version.json! Did you compile with gradle?

it can not find the build info. It is not in the sources, it is generated. This happens when you run it with intellij or ides.

> [2023-12-17 00:29:28.625] [Worker#2] [OTHER] [WARN] java.io.FileNotFoundException: Can not find asset minosoft:mapping/versions.json

That is bad. It should read `\src\main\resources\assets\minosoft\mapping\versions.json`.


What is the command you use to execute gradle? It will only find the assets if you run it either in the same directory (where the build.gradle is) or when you build a fatJar.

**Comment by QaisMalkawi** [comment]
To begin with, I trid to build the project with Intellij IDE and that didn't work for me, so i redownloaded the project so i can start fresh, and built it using the instructions by clicking run.cmd, and it resulted the provided error.

**Comment by QaisMalkawi** [comment]
A little Update, I moved the project to system drive (C://) and it works fine, I don't know what is happenning!

**Comment by Bixilon** [comment]
Interestingly. Both should work just fine.

I don't have any windows here, I will try it when I got access to a machine (from another drive). Thanks for the hint!

**Comment by Bixilon** [comment]
Could be fixed in the `updater` branch.
