### ISSUE TITLE
 no zstd-jni-1.5.2-2 in java.library.path error

### ISSUE THREAD

**Issue by ilkerbey-01** [Bixilon/Minosoft#3]
```
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL] java.lang.UnsatisfiedLinkError: no zstd-jni-1.5.2-2 in java.library.path: C:\Program Files\Eclipse Adoptium\jdk-18.0.1.10-hotspot\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Eclipse Adoptium\jdk-18.0.1.10-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-8.0.312.7-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\Crawen\AppData\Local\Microsoft\WindowsApps;;.
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL] Unsupported OS/arch, cannot find /win/amd64/libzstd-jni-1.5.2-2.dll or load zstd-jni-1.5.2-2 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.2-2 in your system.
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at java.base/java.lang.System.loadLibrary(System.java:2015)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at com.github.luben.zstd.util.Native.load(Native.java:87)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at com.github.luben.zstd.util.Native.load(Native.java:55)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at com.github.luben.zstd.ZstdOutputStreamNoFinalizer.<clinit>(ZstdOutputStreamNoFinalizer.java:18)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at com.github.luben.zstd.ZstdOutputStream.<init>(ZstdOutputStream.java:75)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at com.github.luben.zstd.ZstdOutputStream.<init>(ZstdOutputStream.java:46)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at de.bixilon.minosoft.assets.util.FileAssetsUtil.saveAndGet(FileAssetsUtil.kt:69)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at de.bixilon.minosoft.assets.util.FileAssetsUtil.saveAndGet$default(FileAssetsUtil.kt:50)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at de.bixilon.minosoft.data.player.properties.textures.PlayerTexture.read(PlayerTexture.kt:57)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at de.bixilon.minosoft.gui.eros.util.JavaFXAccountUtil.getAvatar(JavaFXAccountUtil.kt:25)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at de.bixilon.minosoft.gui.eros.main.MainErosController$init$7.invoke(MainErosController.kt:136)
[2022-05-06 20:52:39.968] [JavaFX Application Thread] [OTHER] [FATAL]   at de.bixilon.minosoft.gui.eros.main.MainErosController$init$7.invoke(MainErosController.kt:125)
[2022-05-06 20:52:39.969] [JavaFX Application Thread] [OTHER] [FATAL]   at de.bixilon.minosoft.config.profile.delegate.watcher.SimpleProfileDelegateWatcher$Companion$profileWatchFX$1.invoke$lambda-0(SimpleProfileDelegateWatcher.kt:55)
[2022-05-06 20:52:39.969] [JavaFX Application Thread] [OTHER] [FATAL]   at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
[2022-05-06 20:52:39.969] [JavaFX Application Thread] [OTHER] [FATAL]   at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[2022-05-06 20:52:39.969] [JavaFX Application Thread] [OTHER] [FATAL]   at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
[2022-05-06 20:52:39.969] [JavaFX Application Thread] [OTHER] [FATAL]   at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
[2022-05-06 20:52:39.969] [JavaFX Application Thread] [OTHER] [FATAL]   at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
[2022-05-06 20:52:39.969] [JavaFX Application Thread] [OTHER] [FATAL]   at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
[2022-05-06 20:52:39.969] [JavaFX Application Thread] [OTHER] [FATAL]   at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ant-7802** [comment]
try java 17
https://aws.amazon.com/corretto/

**Comment by Bixilon** [comment]
Interesting. Java 17 will (probably) not bring anything.

the natives for zstd are missing on windows. Somehow related to #2 

I'll grab a windows pc tomorrow and test it myself

**Comment by ilkerbey-01** [comment]
> 

java 17 doesnt work and requires me to use java 18 to run it

**Comment by ilkerbey-01** [comment]
> Interesting. Java 17 will (probably) not bring anything.
> 
> the natives for zstd are missing on windows. Somehow related to #2
> 
> I'll grab a windows pc tomorrow and test it myself

would be amazing, thanks

**Comment by Bixilon** [comment]
Don't have a windows computer here, so I did not test it practically. 

It should be fixed with 015b246e2c8e5b946200ea5ad1330431992df9f6, I added the wrong natives in ca1c73293b7e2b8a616de5102f8b889d44d4b2ed (or GH-2).

Please test it and let me know if it worked for you :)

**Comment by ilkerbey-01** [comment]
https://github.com/ilkerbey-01/Minosoft/runs/6334115400?check_suite_focus=true

**Comment by Bixilon** [comment]
I feel 100% screwed

**Comment by Bixilon** [comment]
Why is it forcing you to use java 18? I am using (and building) it with java 11. That should work.

**Comment by ilkerbey-01** [comment]
> 



> Why is it forcing you to use java 18? I am using (and building) it with java 11. That should work.

It says my build version is older than what its compiled with, its compiled with 55 and I have 52 for some reason

**Comment by Bixilon** [comment]
52 is java 8. That is not supported. 55 is Java 11.

You probably have more than 1 jdk installed.

**Comment by ilkerbey-01** [comment]
ah that explains it, I had both java 8 and 17, I thought I made java 17 default
