### ISSUE TITLE
Errors when playing Minosoft with CubicMC server

### ISSUE THREAD

**Issue by nitram84** [Bixilon/Minosoft#30]
I tried to play Minosoft (latest git) with a local CubicMC server (latest git/0.4.0-beta release, https://github.com/CubicMC/cubic-server). After/during spawning I got the first stacktrace. The second stacktrace happened when I tried to chop some oak leaves.

**Steps to reproduce:**

* start Cubic server locally with `./CubicServer --online-mode false`
* use an offline account in Minosoft
* connect to local server with `Forced version: automatic` and `Releases [x]`. -> version 1.19.3 will be used
* -> first stacktrace should appear when all resources are loaded
* try to chop a tree, in my case oak leaves
* -> second stacktrace should appear

I don't know where the error is located (both parts client and server are in development), but in my opinion Minosoft should validate network messages better and I don't think this should cause stacktraces. A best solution would be a warning: "Protocol error detected: Potentially malicious or cheating server detected. If you are using a server of a third party vendor, you should report this issue. Details: ....". 
This way it would be clear where the issue has to be reported.

I also wasn't able to pick up items (in case of CubicMC some oak leaves (which shouldn't be dropped)). In a second test with a cuberite server (https://github.com/cuberite/cuberite, latest git, protocol version 1.12) I wasn't able to pick up a sapling. Is "picking up items" not yet implemented or is the error server-side?

**Server log:**

```
# ./CubicServer` --online-mode false
[2024-02-18 20:19:30.961] [main] [info] GlobalPalette initialized
[2024-02-18 20:19:30.966] [main] [info] ItemConverter initialized
[2024-02-18 20:19:30.971] [main] [info] SoundEventConverter initialized
[2024-02-18 20:19:30.986] [main] [info] BlockDataConverter initialized
[2024-02-18 20:19:31.021] [main] [info] Loaded 993 loot tables from path assets/loot_tables into namespace "minecraft"
[2024-02-18 20:19:31.047] [main] [info] Loaded 1010 recipes from path assets/recipes into namespace "minecraft"
[2024-02-18 20:19:31.049] [main] [info] Loading plugins from ./plugins...
[2024-02-18 20:19:31.049] [main] [info] Plugins loaded
[2024-02-18 20:19:31.049] [main] [info] Initialize - Overworld
[2024-02-18 20:19:31.049] [main] [info] Initialize - The Nether
[2024-02-18 20:19:31.049] [main] [info] Generating NBT for registry minecraft:chat_type with 7
[2024-02-18 20:19:31.050] [main] [info] Generating NBT for registry minecraft:worldgen/biome with 3
[2024-02-18 20:19:31.050] [main] [info] Generating NBT for registry minecraft:dimension_type with 2
[2024-02-18 20:19:31.050] [main] [info] Master registry initialized with 3 registries
[2024-02-18 20:19:33.628] [WorldGen] [info] Created Furnace with facing: 1 and lit: false
[2024-02-18 20:19:40.858] [main] [info] Overworld initialized
[2024-02-18 20:19:40.858] [main] [info] The Nether initialized
[2024-02-18 20:20:06.766] [main] [info] Player Unnamed_player with uuid ffffffff-f3dc-e451-0000-000000000000 just logged in
```

**Minosoft log:** 

```
[2024-02-18 20:18:53.378] [main] [OTHER] [INFO] Starting minosoft...
[2024-02-18 20:18:53.924] [Worker#4] [OTHER] [INFO] This is minosoft version bef2f86138-dirty, built on bef2f86138/master!
[2024-02-18 20:18:54.153] [CLI] [OTHER] [WARN] Feb 18, 2024 8:18:54 PM org.jline.utils.Log logr
[2024-02-18 20:18:54.153] [CLI] [OTHER] [WARN] WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
[2024-02-18 20:18:54.153] [CLI] [OTHER] [WARN] 
Gtk-Message: 20:18:54.219: Failed to load module "canberra-gtk-module"
[2024-02-18 20:18:54.786] [Worker#6] [OTHER] [WARN] SLF4J(W): No SLF4J providers were found.
[2024-02-18 20:18:54.787] [Worker#6] [OTHER] [WARN] SLF4J(W): Defaulting to no-operation (NOP) logger implementation
[2024-02-18 20:18:54.794] [Worker#6] [OTHER] [WARN] SLF4J(W): See https://www.slf4j.org/codes.html#noProvidersfor further details.
[2024-02-18 20:18:54.951] [CLI] [OTHER] [INFO] A headless input system is available, press tab or type help to see all available commands!
[2024-02-18 20:18:54.957] [main] [GENERAL] [INFO] Minosoft boot sequence finished in 1.7 s!
[2024-02-18 20:18:55.041] [Worker#6] [MOD_LOADING] [INFO] Mod loading completed!

(java:15306): Gdk-WARNING **: 20:18:55.347: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
[2024-02-18 20:18:55.499] [Worker#4] [NETWORK] [INFO] Pinging localhost (from localhost:25565)
[2024-02-18 20:18:55.568] [Worker#6] [NETWORK] [INFO] Pinging localhost (from localhost:25565)
[2024-02-18 20:19:56.795] [Worker#2] [NETWORK] [INFO] Pinging localhost (from localhost:25565)
[2024-02-18 20:20:01.862] [Worker#0] [ASSETS] [INFO] Downloading and verifying assets. This might take a while...
[2024-02-18 20:20:03.106] [Worker#7] [LOADING] [INFO] Registries for 1.19.3 loaded in 944 ms
[2024-02-18 20:20:04.276] [Worker#0] [ASSETS] [INFO] Assets verified!
[2024-02-18 20:20:04.442] [Worker#3] [RENDERING] [INFO] Hello LWJGL 3.3.3+5!
[2024-02-18 20:20:04.443] [Audio#2] [AUDIO] [INFO] Loading OpenAL...
[2024-02-18 20:20:04.615] [Audio#2] [AUDIO] [INFO] OpenAL loaded!
[2024-02-18 20:20:04.998] [Worker#3] [LOADING] [WARN] Can not find item model minecraft:builtin/generated
[2024-02-18 20:20:05.000] [Worker#3] [LOADING] [WARN] Can not find item model minecraft:builtin/entity
[2024-02-18 20:20:05.003] [Worker#3] [LOADING] [WARN] Can not find item model minecraft:builtin/entity
[2024-02-18 20:20:05.008] [Worker#3] [LOADING] [WARN] Can not find item model minecraft:builtin/entity
[2024-02-18 20:20:05.012] [Worker#3] [LOADING] [WARN] Can not find item model minecraft:builtin/entity
[2024-02-18 20:20:05.264] [Rendering#2] [LOADING] [WARN] Can not find skeletal model minecraft:models/entities/pig/piglet.smodel
[2024-02-18 20:20:05.268] [Rendering#2] [LOADING] [WARN] Can not find skeletal model minecraft:models/entities/cow/calf.smodel
[2024-02-18 20:20:06.730] [Rendering#2] [RENDERING] [INFO] Rendering is fully prepared in 2.2 s
[2024-02-18 20:20:06.730] [Rendering#2] [NETWORK] [INFO] Connecting to server: localhost
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] de.bixilon.minosoft.protocol.network.network.client.netty.exceptions.PacketReadException
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.network.network.client.netty.pipeline.encoding.PacketDecoder.decode(PacketDecoder.kt:64)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.network.network.client.netty.pipeline.encoding.PacketDecoder.decode(PacketDecoder.kt:31)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:833)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.s2c.play.chat.CommandsS2CP.<init>(CommandsS2CP.kt:37)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.registry.DefaultPackets$S2C$4$38.create(DefaultPackets.kt:306)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.registry.DefaultPackets$S2C$4$38.create(DefaultPackets.kt:306)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.registry.factory.PlayPacketFactory$DefaultImpls.create(PlayPacketFactory.kt:22)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.registry.DefaultPackets$S2C$4$38.create(DefaultPackets.kt:306)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.registry.PacketType.create(PacketType.kt:37)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.network.network.client.netty.pipeline.encoding.PacketDecoder.decode(PacketDecoder.kt:51)
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 	... 30 more
[2024-02-18 20:20:06.834] [Epoll#1] [NETWORK_IN] [WARN] 
[2024-02-18 20:20:06.886] [Rendering#2] [RENDERING] [INFO] Showing window after 128 ms
[2024-02-18 20:20:06.886] [Rendering#2] [RENDERING] [INFO] Starting loop
[2024-02-18 20:20:08.198] [Epoll#1] [CHAT_IN] [INFO] Unname_player joined the game
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] de.bixilon.minosoft.protocol.network.network.client.netty.exceptions.PacketReadException
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.network.network.client.netty.pipeline.encoding.PacketDecoder.decode(PacketDecoder.kt:64)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.network.network.client.netty.pipeline.encoding.PacketDecoder.decode(PacketDecoder.kt:31)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:833)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] Caused by: java.lang.NullPointerException: Can not get entry with id -1!
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.data.registries.registries.registry.AbstractRegistry$DefaultImpls.get(AbstractRegistry.kt:28)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.data.registries.registries.registry.Registry.get(Registry.kt:32)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.data.registries.registries.registry.Registry.get(Registry.kt:32)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.protocol.buffers.play.PlayInByteBuffer.readRegistryItem(PlayInByteBuffer.kt:281)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.s2c.play.block.BlockDataS2CP.<init>(BlockDataS2CP.kt:37)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.registry.DefaultPackets$S2C$4$15.create(DefaultPackets.kt:277)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.registry.DefaultPackets$S2C$4$15.create(DefaultPackets.kt:277)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.registry.factory.PlayPacketFactory$DefaultImpls.create(PlayPacketFactory.kt:22)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.registry.DefaultPackets$S2C$4$15.create(DefaultPackets.kt:277)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.packets.registry.PacketType.create(PacketType.kt:37)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	at de.bixilon.minosoft.protocol.network.network.client.netty.pipeline.encoding.PacketDecoder.decode(PacketDecoder.kt:51)
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 	... 28 more
[2024-02-18 20:20:55.064] [Epoll#1] [NETWORK_IN] [WARN] 
```

**Comment by Bixilon** [comment]
Thanks for reaching out, just did some tests.

The first exception is valid, the server references a node id that does not exist. The problem is, that there is no option in the minecraft protocol to say, there is no "root node". The only option is to not send the packet. I added a workaround to hide it in that case.

The other expception is totally valid. Only if blocks that actually have data (like chests, ...) the packet should be sent. The server instead sends -1 as id, which is - obviously - invalid. Hence the exception.  Please report both errors to the server developer.

Minosoft actually only "crashes" when an exception occurs while joining, everything else is just logged as warning (in case I or the server does something weird). Just ignore them.

Picking up items is actually a server only thing, the client can not do anything about it (server sends the pick up animation, container change and then kills the entity). 


Cuberite actually works pretty well (try forcing 1.14), all versions below 1.13 are pretty broken, because everything needs to be implemented manualy and I can not realy on tools like pixlyzer (see https://gitlab.bixilon.de/bixilon/minosoft/-/issues/26 for more details). There are probably a ton of exceptions while loading those old versions, but they all can be ignored.


I can actually pick up items in 1.12 on cuberite. Any error?


But thanks for reaching out and giving feedback!

**Comment by nitram84** [comment]
Thank you very much for your response! This helped a lot - I'll report the two issues at the server-side. Your hint with cuberite 1.14 is very helpful for everyone who wants to play oss minecraft. I think you can close this issue. For my "picking-up" problem I'll start a new game following your hint. If I really think there might be an issue on the client-side, I will open a new ticket with more detailed information.

**Comment by Bixilon** [comment]
Sure!
