### ISSUE TITLE
InetAddressResolverProvider error on Java 17 PPC64BE

### ISSUE THREAD

**Issue by iAmInActions** [Bixilon/Minosoft#32]
Hello, I have tried building and running the client on Java 17 under Void Linux on a 64 bit big endian PowerPC machine and am running into the following issue:

```
java.util.ServiceConfigurationError: java.net.spi.InetAddressResolverProvider: Provider org.xbill.DNS.spi.DnsjavaInetAddressResolverProvider not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at java.base/java.util.ServiceLoader.findFirst(ServiceLoader.java:1812)
	at java.base/java.net.InetAddress.loadResolver(InetAddress.java:508)
	at java.base/java.net.InetAddress.resolver(InetAddress.java:488)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1826)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1139)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688)
	at java.base/java.net.InetAddress.getByName(InetAddress.java:1568)
	at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:230)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1252)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1138)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1690)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
	at java.base/java.net.URL.openStream(URL.java:1325)
	at de.bixilon.minosoft.assets.minecraft.index.IndexAssetsManager.downloadAssetsIndex(IndexAssetsManager.kt:72)
	at de.bixilon.minosoft.assets.minecraft.index.IndexAssetsManager.readAssetsIndex(IndexAssetsManager.kt:64)
	at de.bixilon.minosoft.assets.minecraft.index.IndexAssetsManager.load(IndexAssetsManager.kt:97)
	at de.bixilon.minosoft.assets.multi.PriorityAssetsManager.load(PriorityAssetsManager.kt:80)
	at de.bixilon.minosoft.protocol.network.session.play.PlaySession.connect$lambda$11(PlaySession.kt:211)
	at de.bixilon.kutil.concurrent.worker.task.TaskWorker.work$lambda$5(TaskWorker.kt:113)
	at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.run(ThreadPoolExecutor.kt:25)
	at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.execute(ThreadPoolExecutor.kt:44)
	at de.bixilon.kutil.concurrent.pool.ThreadPool.execute(ThreadPool.kt:46)
	at de.bixilon.kutil.concurrent.pool.ThreadPool.plusAssign(ThreadPool.kt:50)
	at de.bixilon.kutil.concurrent.worker.task.TaskWorker.work(TaskWorker.kt:125)
	at de.bixilon.minosoft.protocol.network.session.play.PlaySession.connect(PlaySession.kt:220)
	at de.bixilon.minosoft.gui.eros.main.play.server.ServerListController.connect$lambda$14(ServerListController.kt:206)
	at de.bixilon.minosoft.gui.eros.main.account.AccountController.checkAccount$lambda$10$lambda$9(AccountController.kt:121)
	at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.run(ThreadPoolExecutor.kt:25)
	at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.execute(ThreadPoolExecutor.kt:44)
	at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.loop(ThreadPoolThread.kt:49)
	at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.run(ThreadPoolThread.kt:31)

```

What works:
- Opening the Launcher
- Creating an account
- Adding Servers
- Thumbnail/MOTD

What doesn't work:
- Version detection
- Launching the game

Any help with this would be greatly appreciated.

**Comment by iAmInActions** [comment]
So, I just tried reproducing the error to get a log and for some reason the game just started to work. I did not change anything and I ran it with the same settings and java install as before.

The log:
[log.txt](https://github.com/user-attachments/files/18141102/log.txt)

**Comment by Bixilon** [comment]
Happy to hear! 

(the errors in the console are normal for < 1.13, see https://gitlab.bixilon.de/bixilon/minosoft/-/issues/26)
