### ISSUE TITLE
Some questions about initialization

### ISSUE THREAD

**Issue by wifi-left** [Bixilon/Minosoft#6]
> Verifying and downloading missing assets. This might take a while...

I found that on my computer, initialization (entering the game from the server) takes a long time (**30 minutes and more**) 
I would like to know if there is a way to make this process faster.

*Additional info: It didn't take me that long to reinstall Minecraft using the launcher and start vanilla Minecraft.*

**Thanks.**

**Comment by Bixilon** [comment]
I think you are stuck in a dead lock. Already fixed that in the `work/light` branch. Can you check that branch? If it is working, imma cherry pick 1a7c5d6312a3bc1d1cbc50ff64e655470f96cd00. 

Currently pretty busy with other projects, going to work on light in some days (hopefully). 

If it is not working, clear the `assets` folder, try starting with `--verbose` and set all log levels (in `config/minosoft/*/other.json`) to `VERBOSE`. That will print a lot more information. That could be useful

**Comment by wifi-left** [comment]
After I build it myself, when I load the resource, I get an error:
```
----- Minosoft Crash Report -----
// You can't do this

-- General Information --
    Time: 2022-07-10 00:38:07 (1657384687)
    Crash thread: JavaFX Application Thread

-- Stacktrace --
java.io.FileNotFoundException: Can not find assets-manager for minecraft:lang/en_us.json
	at de.bixilon.minosoft.assets.multi.PriorityAssetsManager.get(PriorityAssetsManager.kt:67)
	at de.bixilon.minosoft.data.language.LanguageManager$Companion.load$loadMinecraftLanguage(LanguageManager.kt:64)
	at de.bixilon.minosoft.data.language.LanguageManager$Companion.load(LanguageManager.kt:87)
	at de.bixilon.minosoft.data.language.LanguageManager$Companion.load$default(LanguageManager.kt:58)
	at de.bixilon.minosoft.protocol.network.connection.play.PlayConnection.connect(PlayConnection.kt:202)
	at de.bixilon.minosoft.gui.eros.main.play.server.ServerListController$connect$1.invoke(ServerListController.kt:185)
	at de.bixilon.minosoft.gui.eros.main.play.server.ServerListController$connect$1.invoke(ServerListController.kt:129)
	at de.bixilon.minosoft.gui.eros.main.account.AccountController.checkAccount$lambda-7$lambda-6(AccountController.kt:122)
	at de.bixilon.kutil.concurrent.pool.ThreadPool.startThreadLoop(ThreadPool.kt:52)
	at de.bixilon.kutil.concurrent.pool.ThreadPool.checkThreads$lambda-1(ThreadPool.kt:74)
	at java.base/java.lang.Thread.run(Thread.java:833)


-- Connections --
    #3:
        Version: 1.19
        Account: wifi_left
        Address: rm.fubuki.vip:25570
        Brand: unknown
        Events: 8
        State: ERROR
        Connected: false
        Protocol state: HANDSHAKING
        Compression threshold: -1
        Encrypted: false
        Was connected: false
        Rendering: false
        Error: java.io.FileNotFoundException: Can not find assets-manager for minecraft:lang/en_us.json
    #4:
        Version: 1.19
        Account: wifi_left
        Address: rm.fubuki.vip:25570
        Brand: unknown
        Events: 8
        State: ERROR
        Connected: false
        Protocol state: HANDSHAKING
        Compression threshold: -1
        Encrypted: false
        Was connected: false
        Rendering: false
        Error: java.io.FileNotFoundException: Can not find assets-manager for minecraft:lang/en_us.json

-- Runtime Details --
    Start arguments: [--verbose]
    JVM flags: []
    Home directory: C:/Users/Gamom/AppData/Roaming/Minosoft/
    Disable Eros: false
    Disable rendering: false

-- System Details --
    Operating system: Windows 10: Windows 64bit
    Detected operating system: WINDOWS
    Detected architecture: AMD64
    Java version: 17.0.1+12-LTS 64bit
    Memory: 7.9 GiB
    CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
 
-- Git Info --
    Uninitialized :(
```
And I found that there is no lang/en_us.json in the official indexes file.

**Comment by Bixilon** [comment]
The "fix" actually did not fix the issue :rofl: 

The language file is not in the assets index, it is in the original minecraft jar (en_us is  the exception).

I implemented a new fix, it works on my side now.

**Comment by wifi-left** [comment]
There is really no such problem, but a new problem has appeared 🤣:
```
java.io.IOException: Decompression error: Unknown frame descriptor
	at com.github.luben.zstd.ZstdInputStreamNoFinalizer.readInternal(ZstdInputStreamNoFinalizer.java:171)
	at com.github.luben.zstd.ZstdInputStreamNoFinalizer.read(ZstdInputStreamNoFinalizer.java:123)
	at com.github.luben.zstd.ZstdInputStream.read(ZstdInputStream.java:88)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:539)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:133)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:256)
	at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1655)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1083)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3682)
	at de.bixilon.minosoft.assets.util.FileUtil.readJsonObject(FileUtil.kt:78)
	at de.bixilon.minosoft.assets.util.FileUtil.readJsonObject$default(FileUtil.kt:76)
	at de.bixilon.minosoft.data.language.LanguageManager$Companion.load$loadMinecraftLanguage(LanguageManager.kt:64)
	at de.bixilon.minosoft.data.language.LanguageManager$Companion.access$load$loadMinecraftLanguage(LanguageManager.kt:55)
	at de.bixilon.minosoft.data.language.LanguageManager$Companion$load$1.invoke(LanguageManager.kt:85)
	at de.bixilon.minosoft.data.language.LanguageManager$Companion$load$1.invoke(LanguageManager.kt:85)
	at de.bixilon.kutil.exception.ExceptionUtil.tryCatch(ExceptionUtil.kt:21)
	at de.bixilon.minosoft.data.language.LanguageManager$Companion.load(LanguageManager.kt:85)
	at de.bixilon.minosoft.data.language.LanguageManager$Companion.load$default(LanguageManager.kt:58)
	at de.bixilon.minosoft.protocol.network.connection.play.PlayConnection.connect(PlayConnection.kt:204)
	at de.bixilon.minosoft.gui.eros.main.play.server.ServerListController$connect$1.invoke(ServerListController.kt:185)
	at de.bixilon.minosoft.gui.eros.main.play.server.ServerListController$connect$1.invoke(ServerListController.kt:129)
	at de.bixilon.minosoft.gui.eros.main.account.AccountController.checkAccount$lambda-11(AccountController.kt:149)
	at de.bixilon.kutil.concurrent.pool.ThreadPool.startThreadLoop(ThreadPool.kt:52)
	at de.bixilon.kutil.concurrent.pool.ThreadPool.checkThreads$lambda-1(ThreadPool.kt:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
I am using **Microsoft OpenJDK 17**

**Comment by wifi-left** [comment]
Other: No problem connecting to 1.18 server, but error connecting to 1.19 server.
And every time you connect to the server, the resource will be re-downloaded (regardless of whether the resource exists locally or not).

**Comment by Bixilon** [comment]
Interesting, not happening to me. It could be, that because of the previous error. Maybe assets are corrupted? Should not happen, they get saved corrupted. 

You can try deleting the `assets` folder again and then retry. 

Maybe another error occurred first, just update to the latest commit. that one will now be logged

**Comment by wifi-left** [comment]
This time there was no error on the resource, but I couldn't get to the server. I'm using the fabric server (not even without mods).
# LOG:
```
[2022-07-10 21:09:52.958] [Nio#8] [NETWORK_PACKETS_OUT] [VERBOSE] Handshake (protocolId=759, hostname=127.0.0.1, port=25565, nextState=LOGIN)
[2022-07-10 21:09:52.958] [Nio#8] [NETWORK_PACKETS_OUT] [VERBOSE] Login start (username=wifi_left, publicKey=de.bixilon.minosoft.protocol.PlayerPublicKey@7ce31e08)
[2022-07-10 21:09:52.964] [Nio#8] [NETWORK_PACKETS_IN] [VERBOSE] Encryption request (serverId=, publicKey=<DELETED>)
[2022-07-10 21:09:54.536] [Nio#8] [AUTHENTICATION] [VERBOSE] Mojang server join successful (username=wifi_left, serverId=<DELETED>)
[2022-07-10 21:09:54.541] [Nio#8] [NETWORK_PACKETS_OUT] [VERBOSE] Encryption response (secret=<DELETED>, nonce=SignatureData(salt=<DELETED>, signature=[<DELETED>]))
[2022-07-10 21:09:55.374] [Nio#8] [NETWORK_PACKETS_IN] [VERBOSE] Compression (threshold=256)
[2022-07-10 21:09:55.376] [Nio#8] [NETWORK_PACKETS_IN] [VERBOSE] Login success (uuid=<DELETED>, name=wifi_left, properties=PlayerProperties(textures=PlayerTextures(name=wifi_left, uuid=<DELETED>, date=Sun Jul 10 21:09:56 CST 2022, skin=de.bixilon.minosoft.data.entities.entities.player.properties.textures.SkinPlayerTexture@5fa698d8, cape=de.bixilon.minosoft.data.entities.entities.player.properties.textures.PlayerTexture@19565612, elytra=null)))
[2022-07-10 21:09:56.694] [Audio#6] [AUDIO_LOADING] [INFO] Unloading OpenAL...
[2022-07-10 21:09:56.694] [Audio#6] [AUDIO_LOADING] [VERBOSE] Unloading sounds...
[2022-07-10 21:09:56.695] [Audio#6] [AUDIO_LOADING] [VERBOSE] Unloading sources...
[2022-07-10 21:09:56.695] [Audio#6] [AUDIO_LOADING] [VERBOSE] Destroying OpenAL context...
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN] de.bixilon.minosoft.protocol.network.network.client.exceptions.PacketReadException
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.protocol.network.network.client.pipeline.encoding.PacketDecoder.decode(PacketDecoder.kt:64)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.protocol.network.network.client.pipeline.encoding.PacketDecoder.decode(PacketDecoder.kt:35)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at java.base/java.lang.Thread.run(Thread.java:833)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN] Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 19 out of bounds for length 13
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.kutil.enums.ValuesEnum$DefaultImpls.get(ValuesEnum.kt:19)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.util.nbt.tag.NBTTagTypes$Companion.get(NBTTagTypes.kt:34)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.util.nbt.tag.NBTTagTypes$Companion.get(NBTTagTypes.kt:34)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.protocol.protocol.InByteBuffer.readNBTTag(InByteBuffer.kt:402)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.protocol.protocol.PlayInByteBuffer.readNBT(PlayInByteBuffer.kt:128)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.data.entities.data.types.GlobalPositionEntityDataType.read(GlobalPositionEntityDataType.kt:26)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.protocol.packets.s2c.play.InitializeS2CP$2.invoke(InitializeS2CP.kt:143)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.protocol.packets.s2c.play.InitializeS2CP$2.invoke(InitializeS2CP.kt:143)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.protocol.protocol.PlayInByteBuffer.readPlayOptional(PlayInByteBuffer.kt:268)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.protocol.packets.s2c.play.InitializeS2CP.<init>(InitializeS2CP.kt:143)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.protocol.packets.factory.factories.ReflectionFactory.createPacket(ReflectionFactory.kt:34)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.protocol.network.network.client.pipeline.encoding.PacketDecoder.readPacket(PacketDecoder.kt:76)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   at de.bixilon.minosoft.protocol.network.network.client.pipeline.encoding.PacketDecoder.decode(PacketDecoder.kt:54)
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]   ... 37 more
[2022-07-10 21:09:56.705] [Nio#8] [NETWORK_PACKETS_IN] [WARN]
[2022-07-10 21:09:56.707] [Audio#6] [AUDIO_LOADING] [INFO] Unloaded OpenAL!
```
# Other questions:
If there is a carpet mod on the server, the log will show the plugin message carpet and it will stagnate, causing the server to send a "login timeout" to eliminate the client.
# More information:
I found that using 1.18 was able to enter the server, and when I first entered, the block had a normal screen. After switching positions, only the edge of the block, no block material (transparent screen).
Using 1.16.5 can enter the server, but there will be a problem with the coordinate position.

**Comment by Bixilon** [comment]
Okay, seems strange. Somehow  the packet is reading wrong nbt data.

So to test this: I need to setup an 1.19 server with fabric, right? I can perfectly join with that.


(but on fabric I also see that some chunks just not get rendered and they don't even appear, going to fix that asap)


Not tested with  that mod, probably it requires the client to send something. Does this mod need to be installed on the client too?

**Comment by wifi-left** [comment]
This mod does not have to be installed on the client. However, if the mod is installed, the server will send a message to the client confirming the version the client is using (vanilla Minecraft will ignore this request).
*(Carpet is fabric's next well-known optimization mod)*

**Comment by Bixilon** [comment]
Ah, did not know that. I'll set it up later and test why it is timing out.

**Comment by Bixilon** [comment]
Sorry to inform you, but: joining a fabric server with that mod works (except those other issues) without a problem

**Comment by Bixilon** [comment]
just read the exception you sent, total different problem, just affecting 1.19 if you already died once. fixed that issue

**Comment by Bixilon** [comment]
2 bugs should be fixed in the `work/light` branch

**Comment by Bixilon** [comment]
Everything should be fixed by now
